### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Nimms159** [LapisRaider/Derpat#1]
running build.bat opens and closes the command prompt without executing main.exe; seeking guidance for resolution.

**Comment by TypeDefinition** [comment]
1. The file build.bat only builds the program, not run it.
2. To build the program, ensure that you have the necessary dependencies installed as per the README.md.
3. **To run the program without building it, download the release version and follow the instructions [here](https://github.com/LapisRaider/Derpat/releases/tag/v1.2).**
4. This project was made for a hackathon 2 years ago, and no further development or support was intended.
5. Who are you and how did you even find this?!
